# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
GOOGLE_API_KEY: AIzaSyAEls9ZDdlcmVmwbAoBjBYHNzZRbzySs0o
DARKSKY_API_KEY: 4bec3a2817f2cb12f43ff6a566f85bbd
AMYPODE_API_KEY: oscar_the_grouch
UNSPLASH_ACCESS_KEY: 2d9f58b410a1a64100360fbe36f74eb4ad3c3f59a5ee49b0330999633ef793e7
UNSPLASH_SECRET_KEY: 0cf26d6c9beca0a1b9bb5303b3f8689d7dfa15fb48863a5ff6f4c5b8a0443904
